# Generated by Django 3.1 on 2020-08-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjust',
            options={'ordering': ('date',)},
        ),
    ]
